package com.melksanj.constants;

import lombok.Getter;
import lombok.RequiredArgsConstructor;

import java.util.Optional;

@RequiredArgsConstructor
@Getter
public enum NeighborhoodEnum {
    GHOLHAK("قلهک", "تهران", 3),
    TOHID("توحید", "تهران", 6),
    ELAHIYEH("الهیه", "تهران", 1),
    DARDASHT("دردشت", "تهران", 8),
    GISHA("گیشا", "تهران", 2),
    SHAHRAK_NAFT_DISTRICT5("شهرک نفت", "تهران", 5),
    KAMRANIYEH("کامرانیه", "تهران", 1),
    SHEMIRAN_NO("شمیران نو", "تهران", 4),
    MAJIDIYEH("مجیدیه", "تهران", 4),
    WEST_TEHRANPARS("تهرانپارس غربی", "تهران", 4),
    TEHRAN_KERMAN("کرمان", "تهران", 8),
    ABOUZAR("ابوذر", "تهران", 17),
    EKHTIYARIYEH("اختیاریه", "تهران", 3),
    FALLAH("فلاح", "تهران", 17),
    JORDAN("جردن", "تهران", 3),
    TAJRISH("تجریش", "تهران", 1),
    NABI_AKRAM("نبی اکرم", "تهران", 14),
    PIROUZI("پیروزی", "تهران", 13),
    HEKMAT("حکمت", "تهران", 1),
    SHAHRAK_E_KIANSHAHR("شهرک کیانشهر", "تهران", 15),
    SARSABIL("سلسبیل", "تهران", 10),
    ABDOL_ABAD("عبدال‌آباد", "تهران", 19),
    JAMALZADEH("جمالزاده", "تهران", 6),
    SOUTH_JANAT_ABAD("جنت‌آباد جنوبی", "تهران", 5),
    NIAVARAN("نیاوران", "تهران", 1),
    TEHRAN_POLICE("پلیس", "تهران", 4),
    OGHAf("اوقاف", "تهران", 4),
    DARROUS("دروس", "تهران", 3),
    OSTAD_MOEIN("استاد معین", "تهران", 9),
    MIRDAMAD("میرداماد", "تهران", 3),
    MOBARAK_ABAD_E_BEHESHTI("مبارک‌آباد بهشتی", "تهران", 4),
    KUHAK("کوهک", "تهران", 22),
    ALMAHDI("المهدی", "تهران", 5),
    NORTH_SOHRAVARDI("سهروردی شمالی", "تهران", 7),
    TEHRANSAR("تهرانسر", "تهران", 21),
    SHAHRAK_E_VALI_E_ASR("شهرک ولی‌عصر", "تهران", 18),
    EKBATAN("اکباتان", "تهران", 5),
    HERAVI("هروی", "تهران", 4),
    CENTRAL_JANAT_ABAD("جنت‌آباد مرکزی", "تهران", 5),
    VARDAVARD("وردآورد", "تهران", 22),
    VELENJAK("ولنجک", "تهران", 1),
    KOOY_E_FERDOS("کوی فردوس", "تهران", 5),
    YOUSEF_ABAD("یوسف‌آباد", "تهران", 6),
    KAREVAN("کاروان", "تهران", 17),
    POONAK("پونک", "تهران", 5),
    SAADAT_ABAD("سعادت‌آباد", "تهران", 2),
    AJOODANIYEH("اجودانیه", "تهران", 1),
    TOLID_DAROO("تولید دارو", "تهران", 18),
    ANDISHEH("اندیشه", "تهران", 5),
    TEHRAN_LASHKAR("لشکر", "تهران", 8),
    SOUTH_SHAHRAN("شهران جنوبی", "تهران", 5),
    AZARBAIJAN("آذربایجان", "تهران", 10),
    DARVAZEH_SHEMIRAN("دروازه شمیران", "تهران", 12),
    DR_HOSHYAR("دکتر هوشیار", "تهران", 9),
    ZAFAR("ظفر", "تهران", 3),
    SATTARKHAN("ستارخان", "تهران", 2),
    TEHRAN_GORGAN("گرگان", "تهران", 7),
    SOLEYMANI("سلیمانی", "تهران", 14),
    BAQERKHAN("باقرخان", "تهران", 10),
    ABBAS_ABAD("عباس‌آباد", "تهران", 6),
    SHADABAD("شادآباد", "تهران", 18),
    NARMAK("نارمک", "تهران", 8),
    FARMANIYEH("فرمانیه", "تهران", 1),
    AFSARIYEH("افسریه", "تهران", 15),
    AMANIYEH("امانیه", "تهران", 3),
    TAXIRANI("تاکسیرانی", "تهران", 14),
    KAZEM_ABAD("کاظم‌آباد", "تهران", 4),
    CHITGAR_LAKE("دریاچه چیتگر", "تهران", 22),
    SHAHRK_SHAHID_BAGHERI("شهرک شهید باقری", "تهران", 22),
    QIAMDASH("قیامدشت", "تهران", 15),
    SHABIRI("شبیری", "تهران", 10),
    ESKANDARI("اسکندری", "تهران", 11),
    BAGH_FEYZ("باغ فیض", "تهران", 5),
    AMIRIYEH("امیریه", "تهران", 11),
    SHAHRK_JANDARMERI("شهرک ژاندارمری", "تهران", 5),
    QASEMABAD("قاسم‌آباد", "تهران", 4),
    SHAHRK_PARVAZ("شهرک پرواز", "تهران", 5),
    SEPEHR("سپهر", "تهران", 5),
    JAVADIYEH("جوادیه", "تهران", 16),
    PASDARAN("پاسداران", "تهران", 3),
    NILOUFAR("نیلوفر", "تهران", 7),
    ZAFARANIYEH("زعفرانیه", "تهران", 1),
    TARASHT("طرشت", "تهران", 2),
    MINA("مینا", "تهران", 14),
    HASHEM_ABAD("هاشم‌آباد", "تهران", 15),
    ZAHIR_ABAD("ظهیرآباد", "تهران", 20),
    CHITGAR("چیتگر", "تهران", 22),
    ERAM("ارم", "تهران", 5),
    SAZAMN_BARNAMEH("سازمان برنامه", "تهران", 5),
    KHAJE_NEZAM_MOLK("خواجه نظام‌الملک", "تهران", 7),
    NORTH_JANAT_ABAD("جنت‌آباد شمالی", "تهران", 5),
    ARJANTIN("آرژانتین", "تهران", 6),
    KOOYE_HEFDAHOM_SHAHRIVAR("کوی هفدهم شهریور", "تهران", 15),
    SHAHRK_TALEGHANI("شهرک طالقانی", "تهران", 15),
    SHAHRK_GHARB("شهرک غرب", "تهران", 2),
    TAYEB("طیب", "تهران", 15),
    TEHRAN_JOLFA("جلفا", "تهران", 3),
    BAZAAR("بازار", "تهران", 12),
    SHAHR_E_ZIBA("شهر زیبا", "تهران", 5),
    SIZDAH_ABAN("سیزده آبان", "تهران", 14),
    SABALAN("سبلان", "تهران", 8),
    SHARARA("شراره", "تهران", 14),
    SOUTH_DEYALAMAN("دیلمان جنوبی", "تهران", 20),
    AZAD_SHAHR("آزادشهر", "تهران", 4),
    NORTH_KAREGAR("کارگر شمالی", "تهران", 6),
    SHOOSH("شوش", "تهران", 15),
    TEHRANVILA("تهران‌ویلا", "تهران", 2),
    MOQADAM("مقدم", "تهران", 17),
    IRANSHAHR("ایرانشهر", "تهران", 6),
    VANAK("ونک", "تهران", 3),
    JEYHOUN("جیحون", "تهران", 3),
    ZEHTABI("زهتابی", "تهران", 7),
    GOMROK("گمرک", "تهران", 12),
    MARZDARAN("مرزداران", "تهران", 4),
    EAST_TEHRANPARS("شرق تهرانپارس", "تهران", 4),
    AMIR_ABAD("امیرآباد", "تهران", 6),
    JAHAD("جهاد", "تهران", 7),
    EIVANAK("ایوانک", "تهران", 7),
    SHAHID_NAVAB_SAFAVI("شهید نواب صفوی", "تهران", 10),
    DOLAT_ABAD("دولت آباد", "تهران", 16),
    QEYTARIYEH("قیتریه", "تهران", 5),
    ENQELAB("انقلاب", "تهران", 7),
    BERYANAK("بریانک", "تهران", 11),
    SADEGHIYEH("صادقیه", "تهران", 16),
    KAN("کان", "تهران", 11),
    AGHDASIEH("اقدسیه", "تهران", 3),
    SHEYKH_AL_RAEIS("شیخ الرئیس", "تهران", 7),
    NAZI_ABAD("نازی آباد", "تهران", 16),
    ELM_O_SANAT("علم و صنعت", "تهران", 7),
    BOLURSAZI("بلورسازی", "تهران", 7),
    JEY("جِی", "تهران", 7),
    SHAMS_ABAD("شمس آباد", "تهران", 15),
    MAHMOODIYEH("محمودیّه", "تهران", 1),
    SOHANAK("سوهانک", "تهران", 4),
    MOLAVI("مولوی", "تهران", 12),
    DARYA("دریا", "تهران", 12),
    ABOOZAR("ابوزر", "تهران", 12),
    TEHRAN_EMAMAT("تهران امامات", "تهران", 12),
    NEJATOLLAHI("نجات‌اللهی", "تهران", 6),
    HASHEMI("هاشمی", "تهران", 5),
    SHIVA("شیوا", "تهران", 5),
    SALAMAT("سلامت", "تهران", 7),
    SEYED_KHANDAN("سیدخندان", "تهران", 12),
    ZARKESH("زَرکش", "تهران", 4),
    HASAN_ABAD_BAQER_FAR("حسن‌آباد باقرفر", "تهران", 11),
    DOOLAB("دولاب", "تهران", 14),
    ABSHAR_TEHRAN("آبشار تهران", "تهران", 18),
    DEHKADE_OLYMPIC("دهکده المپیک", "تهران", 2),
    WEST_SHAHRAK_E_GOLESTAN("شهرک گلستان غرب", "تهران", 2),
    EAST_SHAREQ("شرق شرقی", "تهران", 3),
    SHAHIN("شاهین", "تهران", 12),
    TEHRAN_ZANJAN("تهران زنجان", "تهران", 13),
    KHAZANEH("خزانه", "تهران", 14),
    CHIZAR("چیزر", "تهران", 11),
    ABDOLLAH_ABAD("عبدالله‌آباد", "تهران", 9),
    ZAMZAM("زمzam", "تهران", 16),
    HOR_SQUARE("میدان هُر", "تهران", 6),
    IMAMZADEH_HASAN("امامزاده حسن", "تهران", 13),
    SHAHED("شاهد", "تهران", 7),
    JAVANMARD_E_GHASAB("جوانمرد قساب", "تهران", 13),
    DEZASHIB("دزاشیب", "تهران", 3),
    SHAHADAT("شهادت", "تهران", 12),
    JAVADIYEH_TEHRAN_PARS("جوادیه تهرانپارس", "تهران", 4),
    NOSRAT("نصرت", "تهران", 7),
    KHANI_ABAD_NO("خانی‌آباد نو", "تهران", 15),
    SHAHRAK_E_KOOHSAR("شهرک کوهسار", "تهران", 3),
    SHAHRAK_NAFT("شهرک نفت", "تهران", 9),
    HASAN_ABAD_SHOMALI("حسن‌آباد شمالی", "تهران", 4),
    CHARSD_DASTGAH("چهارصد دستگاه", "تهران", 11),
    DARABAD("دارآباد", "تهران", 1),
    SHADMAN("شادمَن", "تهران", 12),
    QOBA("قبا", "تهران", 6),
    KOSAR("کوثر", "تهران", 14),
    TAVANIR("توانیر", "تهران", 5),
    SHARIF("شریف", "تهران", 6),
    MOSHIRIYEH("مشیریه", "تهران", 7),
    HAFTCHENAR("هفت‌چنار", "تهران", 4),
    AREF("آرف", "تهران", 7),
    ESTAKHR("استخر", "تهران", 4),
    IMAM_SAJJAD("امام سجاد", "تهران", 7),
    ESHRAT_ABAD("اشرت‌آباد", "تهران", 10),
    SARASIAB_DOOLAB("سراسیاب دولاب", "تهران", 14),
    GOLCHIN("گلچین", "تهران", 12),
    BAHAR("بهار", "تهران", 13),
    HESAR_BOALI("حصار بو علی", "تهران", 1),
    ARAJ("آراج", "تهران", 9),
    AMINHOZOUR("امین‌حضور", "تهران", 7),
    SOUTH_ALI_ABAD("جنوب علی‌آباد", "تهران", 9),
    KHALIJ_E_FARS("خلیج فارس", "تهران", 11),
    MASOUDIEH("مسعودیه", "تهران", 15),
    SHAHID_DASTGHEYB("شهید دستغیب", "تهران", 16),
    ATABAK("اتابک", "تهران", 8),
    ASEMAN("آسمان", "تهران", 7),
    MORAD_ABAD("مرادآباد", "تهران", 6),
    BAHARESTAN("بهارستان", "تهران", 12),
    OZGOL("اوزگل", "تهران", 10),
    NORTH_SHAHRAN("شهران شمالی", "تهران", 6),
    TEHRAN_NO("تهران نو", "تهران", 7),
    ARARAT("آرات", "تهران", 14),
    UNIVERSITY_OF_SHARIF("دانشگاه شریف", "تهران", 4),
    FIROOZABADI("فیروزآبادی", "تهران", 4),
    SHAHRAK_DANESHGAH_TEHRAN("شهرک دانشگاه تهران", "تهران", 1),
    SOLEYMANYEH("سلیمانیّه", "تهران", 5),
    SHARIFABAD("شریف‌آباد", "تهران", 11),
    SHAMSHIRI("شمشیری", "تهران", 7),
    DARYAN_NO("دریان نو", "تهران", 10),
    NEZAM_ABAD("نظام‌آباد", "تهران", 4),
    HAMZEH_ABAD("حمزه‌آباد", "تهران", 9),
    SAZMAN_AB("سازمان‌آب", "تهران", 9),
    KHANI_ABAD("خانی‌آباد", "تهران", 15),
    SHAHRAK_E_ABOOZAR("شهرک ابوذر", "تهران", 5),
    SARSABZ("سارسابز", "تهران", 11),
    FERDOWSI("فردوسی", "تهران", 4),
    TEHRAN_SHANDIZ("تهران شاندیز", "تهران", 5),
    DOLATKHAH("دولت‌خواه", "تهران", 9),
    JABERI("جابری", "تهران", 12),
    AZARI("آذری", "تهران", 8),
    HESHAMATIYEH("هشامتیه", "تهران", 6),
    BAHARAN("بهاران", "تهران", 11),
    SHAHRAK_E_MAHALATI("شهرک محلاتی", "تهران", 7),
    QALAMESTAN("قلمستان", "تهران", 3),
    NEMAT_ABAD("نعمت‌آباد", "تهران", 12),
    KASHANAK("کاشانک", "تهران", 14),
    SHAHRAK_E_FERDOWS("شهرک فردوس", "تهران", 5),
    BAQ_E_AZARI("باق آذری", "تهران", 6),
    HAFT_HOZ("هفت‌حوض", "تهران", 15),
    ESLAM_ABAD("اسلام‌آباد", "تهران", 9),
    SAHEB_AL_ZAMAN("صاحب‌الزمان", "تهران", 13),
    NIROO_HAVAYI("نیرو هوایی", "تهران", 3),
    EMAM_HOSSEIN("امام حسین", "تهران", 10),
    HAKIMIYEH("حکیمیه", "تهران", 7),
    VALIASR("ولیعصر", "تهران", 1),
    SOUTH_NARMAK("جنوب نارمک", "تهران", 7),
    VAHIDIYEH("وحیدیه", "تهران", 14),
    FADAK("فدک", "تهران", 8),
    PAMENAR("پامنار", "تهران", 9),
    MONIRIYEH("منیریه", "تهران", 13),
    KUY_FARAZ("کوچه فراز", "تهران", 5),
    ETEHAD("اتحاد", "تهران", 11),
    SHAHAREK_E_SHARIYATI("شهرک شریعتی", "تهران", 2),
    BOLVAR_E_KESHAVARZ("بولوار کشاورز", "تهران", 7),
    SHAHRAK_E_AZADI("شهرک آزادی", "تهران", 4),
    DABESTAN("دبستان", "تهران", 12),
    KHAVARAN("خاوران", "تهران", 14),
    MAKHSOUS("مخصوص", "تهران", 5),
    JOMHOURI("جمهوری", "تهران", 2),
    TEHRAN_HESARAK("تهران حصارک", "تهران", 8),
    FARAH_ABAD("فرآباد", "تهران", 15),
    BAGH_FERDOWS("باغ فردوس", "تهران", 11),
    SHAHID_AVINI("شهید آوینی", "تهران", 3),
    SAR_ASIAB_MEHR_ABAD("سراسیاب مهرآباد", "تهران", 6),
    YAFTABAD("یافت‌آباد", "تهران", 13),
    JAMARAN("جماران", "تهران", 2),
    ARAMANEH("آرامانه", "تهران", 15),
    PARASTAR("پرستار", "تهران", 10),
    MINABI("مینابی", "تهران", 4),
    YAKHCHI_ABAD("یخچال‌آباد", "تهران", 8),
    SARTAKHT("سرتخت", "تهران", 9),
    EMAMZADEH_QASEM("امامزاده قاسم", "تهران", 10),
    SHEYKH_HADI("شیخ هادی", "تهران", 1),
    TEHRAN_HOSEIN_ABAD("حسین‌آباد تهران", "تهران", 12),
    SANGLAJ("سنگلج", "تهران", 11),
    SIROUS("سیروس", "تهران", 6),
    ASHTIYANI("اشتیانی", "تهران", 7),
    SAD_DASTGAH("صد دستگاه", "تهران", 9),
    JALILI("جلیلی", "تهران", 8),
    EVIN("اوین", "تهران", 1),
    HAFEZIE("حافظیه", "تهران", 5),
    QIAM("قیام", "تهران", 10),
    TOUS("طوس", "تهران", 8),
    SHAHRAK_E_EMAMKHOMENI("شهرک امام‌خمینی", "تهران", 3),
    SAFAIYE("صفاییه", "تهران", 4),
    GANDI("گندی", "تهران", 10),
    DEHQAN("دهقان", "تهران", 7),
    HAVANIROOZ("هوانیروز", "تهران", 9),
    BEHDASHT("بهداشت", "تهران", 5),
    SHAHRAK_E_ESTEQLAL("شهرک استقلال", "تهران", 3),
    KHAK_SEFID("خاک سفید", "تهران", 13),
    SHAHRAK_E_TAKHTI("شهرک تختی", "تهران", 14),
    BISIM("بی‌سیم", "تهران", 6),
    DARBAND("دربند", "تهران", 1),
    BEHJAT_ABAD("بهجت‌آباد", "تهران", 6),
    SOUTH_MEHRABAD("جنوب مهرآباد", "تهران", 16),
    MANSOURIYEH("منصوریه", "تهران", 15),
    TASLIHAT("تسهیلات", "تهران", 4),
    AZADI_SPORT_COMPLEX("مجتمع ورزشی آزادی", "تهران", 22),
    TEHRAN_IRAN("تهران ایران", "تهران", 5),
    BAGH_KHAZANEH("باغ خزانه", "تهران", 20),
    AHANG("آهنگ", "تهران", 14),
    EBRAHIM_ABAD("ابراهیم‌آباد", "تهران", 7),
    LAVIZAN("لویزان", "تهران", 4),
    GHANAT_KOSAR("قنات‌کوشار", "تهران", 6),
    SHOKOOFEH("شکوفه", "تهران", 10),
    KOOYE_E_BIMEH("کوچه بیمه", "تهران", 3),
    HASSAN_ABAD("حسن‌آباد", "تهران", 2),
    VASFENARD("وسفنارد", "تهران", 5),
    SHAHRAK_E_VILASHAHR("شهرک ویلاشهر", "تهران", 19),
    HEZARSANG("هزارسنگ", "تهران", 18),
    SHAHRAK_E_OMID("شهرک امید", "تهران", 21),
    AMIR_BAHADOR("امیر بهادور", "تهران", 9),
    TEHRAN_UNIVERSITY("دانشگاه تهران", "تهران", 6),
    SHAHRAK_E_CHESHMEH("شهرک چشمه", "تهران", 13),
    EBN_BABEVAYH("ابن‌بابویه", "تهران", 8),
    SHAHRAK_GOLHA("شهرک گلها", "تهران", 12),
    FARAHZAD("فرازاد", "تهران", 14),
    SHAHRAK_E_VALFAJR("شهرک والفجر", "تهران", 5),
    BAHMAN_YAR("بهمن‌یار", "تهران", 19),
    SHAHID_ASADI("شهید اسدی", "تهران", 3),
    MAJID_ABAD("مجیدآباد", "تهران", 9),
    SHAHRARAK_E_MOSLEMIN("شهرک مسلمین", "تهران", 15),
    DARB_DOWOM("درب دوم", "تهران", 6),
    MOTAHARI("مطهری", "تهران", 7),
    ZARGANDEH("زرگنده", "تهران", 10),
    MEHRABAD_AIRPORT("فرودگاه مهرآباد", "تهران", 17),
    ABSHAR("آبشار", "تهران", 7),
    QEZEL_QALEH("قزل‌قلعه", "تهران", 3),
    VANAK_VILLAGE("دهکده ونک", "تهران", 9),
    PARVAZ("پرواز", "تهران", 12),
    FATH("فتح", "تهران", 11),
    GOLAB_DAREH("گلاب‌دوره", "تهران", 15),
    SHIAN("شیان", "تهران", 7),
    SHAHID_BORUJERDI("شهید بروجردی", "تهران", 5),
    SHAHRAK_PASDARAN("شهرک پاسداران", "تهران", 4),
    ZAHEED_GILANI("زاهد گیلانی", "تهران", 13),
    SHIRAZI("شیرازی", "تهران", 8),
    ESFANDYARI("اسفندیاری", "تهران", 2),
    KARIM_ABAD("کریم‌آباد", "تهران", 15),
    TEHRAN_KHAGHANI("تهران خاقانی", "تهران", 10),
    DARAKEH("درازک", "تهران", 1),
    MESGAR_ABAD("مسگرآباد", "تهران", 13),
    SAEED_ABAD("سعیدآباد", "تهران", 4),
    SHAHRAK_FARHANGIAN("شهرک فرهنگ‌گان", "تهران", 9),
    SHAHRAK_E_ANSAR("شهرک انصار", "تهران", 15),
    SORKHE_HESAR("سرخه‌حصار", "تهران", 16),
    SHAHRAK_E_DARYA("شهرک دریا", "تهران", 7),
    KUY_NOBONYAD("کوئ نوبنیاد", "تهران", 10),
    SHAHRAK_E_APADANA("شهرک آپادانا", "تهران", 13),
    MALEK_ABAD("ملک‌آباد", "تهران", 5),
    QASR_E_FIROOZEH_YEK("قصر فیروزه یک", "تهران", 3),
    EAST_SALEH_ABAD("شرق صالح‌آباد", "تهران", 4),
    SHAHRAK_E_SHARIFI("شهرک شریفی", "تهران", 8),
    ZEYNABEIYEH("زینبیه", "تهران", 9),
    SHAHRAK_E_GHAZALI("شهرک غزالی", "تهران", 6),
    SHAHRAK_DANESHGAHI("شهرک دانشگاہی", "تهران", 13),
    BAQ_E_REZAVAN("باقی رضوان", "تهران", 11),
    QASR_E_FIROOZEH_DO("قصر فیروزه دو", "تهران", 2);


    private final String persianName;
    private final String city;
    private final Integer region;


    public static Integer getNeighborhoodByCity(String neighborhood, String city) {
        NeighborhoodEnum neighborhoodEnum = Optional.of(NeighborhoodEnum.valueOf(neighborhood.toUpperCase()))
                .orElse(null);
        if (neighborhoodEnum.getCity().equals(city))
            return neighborhoodEnum.getRegion();
        else return 0;
    }

    public static String getPersonaNameByName(String name) {
        return Optional.of(valueOf(name.toUpperCase()).getPersianName()).orElse("نا مشخص");
    }

}

