spring:
  application:
    name: melksanj-ai
  datasource:
    url: jdbc:postgresql://metro.proxy.rlwy.net:36748/railway?sslmode=require
    username: postgres
    password: NHQPQrJQIONSsOoGIKfzVQaKsggjwPfC
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  sql:
    init:
      mode: always
  h2:
    console:
      enabled: true


