spring:
  application:
    name: melksanj-ai
  datasource:
    url: jdbc:postgresql://switchyard.proxy.rlwy.net:28893/railway
    username: postgres
    password: BrgmUziKvYVUrlawBgVjZCtATwdhPDAe
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  sql:
    init:
      mode: always
  h2:
    console:
      enabled: true
openai:
  api:
    key: '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'

