spring:
  application:
    name: melksanj-ai
  datasource:
    url: jdbc:postgresql://switchyard.proxy.rlwy.net:28893/railway
    username: postgres
    password: BrgmUziKvYVUrlawBgVjZCtATwdhPDAe
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  sql:
    init:
      mode: always
  h2:
    console:
      enabled: true
logging:
  level:
    root: trace

